### ISSUE TITLE
BGM機能で、エラーが発生した際にリカバリーが効かない

### ISSUE THREAD

**Issue by mtripg6666tdr** [mtripg6666tdr/Discord-SimpleMusicBot#1757]
音声ソースの最後のキャッシュの有効期限が切れた際に発生するエラーのあと、自動的に再取得して再生する際に失敗している模様
発生するエラー
```
TypeError: Cannot read properties of undefined (reading 'basicInfo')
TypeError: Cannot read properties of undefined (reading 'basicInfo')
    at PlayManagerWithBgm.play (/app/dist/Component/PlayManager.js:148:66)
    at PlayManagerWithBgm.replacementMethod (/app/dist/logger.js:176:37)
    at PlayManagerWithBgm.play (/app/dist/Component/PlayManagerWithBgm.js:55:22)
    at PlayManagerWithBgm.onStreamFailed (/app/dist/Component/PlayManager.js:614:28)
    at PlayManagerWithBgm.handleError (/app/dist/Component/PlayManager.js:505:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by mtripg6666tdr** [comment]
#1875 で解決された模様

**Comment by mtripg6666tdr** [comment]
https://github.com/mtripg6666tdr/Discord-SimpleMusicBot/pull/2010 で追加修正。
